### ISSUE TITLE
Endpoint methods constants

### ISSUE THREAD

**Issue by yaroslavche** [jasny/switch-route#7]
Can `Endpoint` contain constants for allowed methods?

```php
   #\Jasny\SwitchRoute\Endpoint
    const METHOD_HEAD = 'HEAD';
    const METHOD_GET = 'GET';
    const METHOD_POST = 'POST';
    const METHOD_PUT = 'PUT';
    const METHOD_PATCH = 'PATCH';
    const METHOD_DELETE = 'DELETE';
    const METHOD_PURGE = 'PURGE';
    const METHOD_OPTIONS = 'OPTIONS';
    const METHOD_TRACE = 'TRACE';
    const METHOD_CONNECT = 'CONNECT';
```

In this case, we can simply use `Endpoint :: METHOD_ *` anywhere without fear of mis-naming. Also possible implement something like:

```php
    #\Jasny\SwitchRoute\Endpoint::isAvailableMethod
    private function isAvailableMethod(string $method): bool
    {
        return $method === @constant(sprintf('%s::METHOD_%s', __CLASS__, $method));
    }
```

and then check method and remove the initialization in uppercase:

```php
    #\Jasny\SwitchRoute\Endpoint::withRoute
    public function withRoute(string $method, $route, array $vars): self
    {
        if (!$this->isAvailableMethod($method)) {
            throw new InvalidRouteException("Unknown route method '$method'", 1);
        }
        if (isset($this->routes[$method])) {
            throw new InvalidRouteException("Duplicate route for '$method {$this->path}'");
        }

        $copy = clone $this;
        $copy->routes[$method] = $route;
        $copy->vars[$method] = $vars;

        return $copy;
    }
```

As you can see, this is also an example of why we also need to check a code (https://github.com/jasny/switch-route/pull/3#discussion_r318522671). But of course, you can add one more exception, but it looks good. Just specify a subtype by code.

**Comment by jasny** [comment]
The method part of the route as `"POST|PUT /foo/bar"`. I don't see how making it a constant will help. Also, it can be anything, not just these predefined ones.

P.S. Using `@` is highly discouraged.

**Comment by yaroslavche** [comment]
> Using `@` is highly discouraged.

 when you don't know why it used. `constant` triggers warning, if not found. We don't need check that behavior and just compare both. supress warning and compare. that's all. Sure, you can check by other methods. This is not bad in this case, IMO
