### ISSUE TITLE
Question about Scrutinizer configuration...

### ISSUE THREAD

**Issue by shmax** [jasny/switch-route#8]
Sorry to come out of nowhere with this, but I hope you don't mind if I ask a question about your scrutinizer.yml configuration.

I contribute to a number of PHP projects that use Scrutinizer, and we're fed-up with its proprietary static checker. While we generally like Scrutinizer's UI for displaying issues, we would prefer to use PHPStan (and _only_ PHPStan) for static checking.  According to the Scrutinizer [documentation](https://scrutinizer-ci.com/docs/tools/custom-commands/), it is possible to specify any style checkers, and as long as they output the expected "checkstyle" format, they are compatible with Scrutinizer's reporting, and can complement (or replace) the native checkers performed by "php-scrutinizer-run".

Amazingly, after doing a very targeted [github search](https://github.com/search?utf8=%E2%9C%93&q=file+format+phpstan+analysis++analyze+filename%3Ascrutinizer.yml&type=Code), your 3 repos are the only ones that seem to be attempting to configure phpstan this way.

So, to get around to my question: does this work for you? I can't seem to figure out how this is supposed to surface in the Scrutinizer UI. I've set up my repo the same way ([in a PR branch](https://github.com/webonyx/graphql-php/pull/569/files)), and I know that my "phpstan-checkstyle.xml" is being generated and stuffed with errors, but I don't see any hint of the generated information in the Scrutinizer interface. 

I notice that you both use phpstan _and_ run `php-scrutinizer-run`. Why is that? Are you also having trouble getting the phpstan reports to display?

Sorry to bomb you at random with all these questions, and I'll understand if you choose not to get involved.

**Comment by jasny** [comment]
Sorry for the late reply, I hope it's still relevant.

Scrutinizer finds issues that phpstan can't detect, so it's valuable to return both. Also, it gives a "crap" score based on cyclomatic complexity vs test coverages.

The errors should just show up under 'inspections > issues' (as [seen here](https://scrutinizer-ci.com/g/jasny/switch-route/inspections/86b1cf22-f00d-4484-8eb6-8eb3a24e2162/issues/files/src/Generator.php)).

```
Property Jasny\SwitchRoute\Generator::$generateCode has no typehint specified.
```

This is an issue reported by PHPStan, not the Scrutinizer analyzer

```
Note: Using configuration file /home/arnold/Projects/reboot-php/switch-route/phpstan.neon.
 12/12 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ --------------------------------------------------------------------- 
  Line   Generator.php                                                        
 ------ --------------------------------------------------------------------- 
  17     Property Jasny\SwitchRoute\Generator::$generateCode has no typehint  
         specified.                                                           
 ------ --------------------------------------------------------------------- 

 [ERROR] Found 1 error
```

P.S. If you want to reach me use Twitter (https://twitter.com/ArnoldDaniels) and not an GitHub issues.
